# Generated by Django 5.2.5 on 2025-09-08 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('tools', 'Tools')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
