# Generated by Django 5.2.5 on 2025-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clothing", "Clothing"),
                    ("Shoes", "Shoes"),
                    ("Tools", "Tools"),
                ],
                default="update",
                max_length=20,
            ),
        ),
    ]
